server:
  port: 9003

spring:
  application:
    name: dispatch-service
  cloud:
    function:
      definition: prepare|dispatch
    stream:
      bindings:
        preparedispatch-in-0:
          destination: order-accepted
          group: ${spring.application.name}
        preparedispatch-out-0:
          destination: order-dispatched
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

info:
  system: Ticket-service

management:
  endpoints:
    web:
      exposure:
        include: bindings, configprops, env, functions, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}