version: "3.8"
services:
  store-rabbitmq:
    image: rabbitmq:3.10-management
    container_name: store-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf