apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  template:
    spec:
      containers:
        - name: order-service
          volumeMounts:
            - name: postgres-credentials-volume-order
              mountPath: /workspace/secrets/postgres/order
            - name: rabbitmq-credentials-volume
              mountPath: /workspace/secrets/rabbitmq
            - name: keycloak-issuer-resourceserver-secret-volume
              mountPath: /workspace/secrets/keycloak
      volumes:
        - name: postgres-credentials-volume-order
          secret:
            secretName: store-postgres-order-credentials
        - name: rabbitmq-credentials-volume
          secret:
            secretName: store-rabbitmq-credentials
        - name: keycloak-issuer-resourceserver-secret-volume
          secret:
            secretName: keycloak-issuer-resourceserver-secret