spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/ticket_db
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  application:
    name: ticket-service
  cloud:
    stream:
      bindings:
        reserveOrder-in-0:
          destination: seat-reserved
          group: { spring.application.name }
server:
  port: 9001
ticket:
  greeting: Hello on our new ticket service!